### PR TITLE
Add i18n support

### PR DESCRIPTION
**Pull request by llunariis**

### CODE REVIEW

**Comment by JoshAtticus** [comment]
Is this still being updated?

**Comment by theycallhermax** [comment]
> Is this still being updated?

yes

**Comment by JoshAtticus** [comment]
> > Is this still being updated?
> 
> yes

ok

**Comment by theycallhermax** [comment]
closing as bettermeower is discontinued, and this will be backported to meower svelte

**Comment by JoshAtticus** [comment]
> closing as bettermeower is discontinued, and this will be backported to meower svelte

BetterMeower isn't permanently discontinued, it's just a financial issue as of now

**Comment by JoshAtticus** [comment]
@mdwalters

**Comment by theycallhermax** [comment]
> > closing as bettermeower is discontinued, and this will be backported to meower svelte
> 
> BetterMeower isn't permanently discontinued, it's just a financial issue as of now

ok but what about neon?

**Comment by JoshAtticus** [comment]
> > > closing as bettermeower is discontinued, and this will be backported to meower svelte
> > 
> > 
> > BetterMeower isn't permanently discontinued, it's just a financial issue as of now
> 
> ok but what about neon?

Well we have the financial problem solved so Neon is not discontinued, and if making any changes I would recommend making them to NeonClient

**Comment by JoshAtticus** [comment]
ClassicClient is now deprecated. Please move this to the new NeonClient @mdwalters

**Comment by theycallhermax** [comment]
OK, I'll just end first-party i18n support and port it to Neon I guess

Max Walters
PGP key: https://keybase.io/pancake_flipper/pgp_keys.asc
Links: ***@***.***

**Pull request closed without merging**
